site_name: Documentation
repo_url: ""
edit_uri: ""
#site_url: "https://test-lumi-supercomputer-docs.rahtiapp.fi/" #hasn't been chosen yet
site_description: >-
  Instructions, user guides and tutorials for the use of the LUMI supercomputer
copyright: Copyright &copy; 2021 LUMI User Support Team
nav:
  - Intro: 
    - Welcome: index.md
  - First steps: 
    - Get Started: firststeps/getstarted.md
    - Access to LUMI: firststeps/accessLUMI.md
    - Setting up SSH key pair: firststeps/SSH-keys.md
    - Logging in (with SSH client): firststeps/loggingin.md
    - Moving data to/from LUMI: storage/moving/scp-rsync.md
    - Next steps: firststeps/nextsteps.md
  - Hardware:
    - Overview: overview/overview.md
    - Interconnect: computing/interconnect.md
    - Compute nodes:
      - CPU nodes - LUMI-C: computing/systems/lumic.md
      - GPU nodes - LUMI-G: computing/systems/lumig.md
      - Data analytics nodes - LUMI-D: computing/systems/lumid.md
      - GPU Early Access Platform: eap/index.md
    - Storage:
      - Main storage - LUMI-P: storage/parallel/lumip.md
      - Flash storage - LUMI-F: storage/parallel/lumif.md
      - Object storage - LUMI-O: storage/object/index.md
    - Auxiliary platforms:
      - Container Orchestration Platform - LUMI-K: computing/auxiliary/lumik.md
  - Run jobs:
      - Overview: runjobs/overview.md
      - LUMI Environment:
        - Module environment: computing/Lmod_modules.md
        - Software stacks: computing/softwarestacks.md
        - Data storage options: storage/storing-data.md
        - Billing policy: computing/jobs/billing.md
      - Scheduled jobs - SLURM jobs:      
        - Slurm quickstart: computing/jobs/slurm-quickstart.md
        - Slurm partitions: computing/jobs/partitions.md
        - Batch jobs: computing/jobs/batch-job.md
        - Array jobs: computing/jobs/throughput.md
        - Interactive Slurm jobs: computing/jobs/interactive.md
        - Container jobs: software/containers/cray_mpich.md
        - Distribution & binding options: computing/jobs/distribution-binding.md
        - Julia scheduled jobs: software/containers/julia.md
  - Software:
    - Overview: software/index.md
    - Installing software:
      - EasyBuild: software/installing/easybuild.md
      - Spack: software/installing/spack.md
      - Container wrapper: software/containers/wrapper.md
    - Containers: 
      - Singularity/Apptainer containers: computing/containers.md
    - Software guides:
      - VASP: software/packages/vasp.md
      - Quantum ESPRESSO: software/packages/quantumespresso.md
  - Developing:
    - Overview: development/index.md
    - Compiling:
      - Programming environment: development/compiling/prgenv.md
      - Cray compilers: development/compiling/cce.md
      - GNU compilers: development/compiling/gnu.md
    - High performance libraries: 
      - Cray libraries: development/compiling/libraries.md
    - Optimizing for LUMI:
      - Using hugepages: development/compiling/hugepages.md
    - Debugging:
      - Parallel debugging: development/debugging/gdb4hpc.md
      - Memory debugging: development/debugging/valgrind4hpc.md
      - Crash or deadlock: development/debugging/stat-atp.md
    - Performance analysis:
      - Performance analysis strategies: development/profiling/index.md
      - Cray Performance Analysis Tool: development/profiling/perftools.md
  - Help desk: 
    - Help desk: generic/helpdesk.md
    - Training and events: generic/training.md
    - Known issues: issues/index.md
    
 
theme:
  name: material
  greetings: Welcome to the LUMI Documentation
  custom_dir: mkdocs_lumi/
  language: en
  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.annotate
  
  palette:
    scheme: default
    primary: lumi
    accent: lumi

  font: false
  
  favicon: assets/favicon.png

  icon:
    logo: logo
  
  home_primary:
    title: Get Started
    page: firststeps/getstarted-new/
  home_secondary:
    title: To LUMI Main Page
    page: https://lumi-supercomputer.eu/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lumi-supercomputer
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LUMIhpc

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
