site_name: Documentation
repo_url: ""
edit_uri: ""
#site_url: "https://test-lumi-supercomputer-docs.rahtiapp.fi/" #hasn't been chosen yet
site_description: >-
  Instructions, user guides and tutorials for the use of the LUMI supercomputer
copyright: Copyright &copy; 2021 LUMI User Support Team
nav:
  - Intro: 
    - Welcome: index.md
  - First steps: 
    - Get Started: firststeps/getstarted.md
    - Access to LUMI: firststeps/accessLUMI.md
    - Setting up SSH key pair: firststeps/SSH-keys.md
    - Logging in (with SSH client): firststeps/loggingin.md
    - Moving data to/from LUMI: firststeps/movingdata.md
    - Next steps: firststeps/nextsteps.md
  - Hardware:
    - Overview: hardware/index.md
    - Interconnect: hardware/interconnect.md
    - Compute nodes:
      - CPU nodes - LUMI-C: hardware/compute/lumic.md
      - GPU nodes - LUMI-G: hardware/compute/lumig.md
      - Data analytics nodes - LUMI-D: hardware/compute/lumid.md
      - GPU Early Access Platform: hardware/compute/eap.md
    - Storage:
      - Main storage - LUMI-P: hardware/storage/lumip.md
      - Flash storage - LUMI-F: hardware/storage/lumif.md
      - Object storage - LUMI-O: hardware/storage/lumio.md
    - Auxiliary platforms:
      - Container Orchestration Platform - LUMI-K: hardware/auxiliary/lumik.md
  - Run jobs:
      - Overview: runjobs/index.md
      - LUMI Environment:
        - Module environment: runjobs/lumi_env/Lmod_modules.md
        - Software stacks: runjobs/lumi_env/softwarestacks.md
        - Data storage options: runjobs/lumi_env/storing-data.md
        - Billing policy: runjobs/lumi_env/billing.md
      - Scheduled jobs - SLURM jobs:      
        - Slurm quickstart: runjobs/scheduled-jobs/slurm-quickstart.md
        - Slurm partitions: runjobs/scheduled-jobs/partitions.md
        - Batch jobs: runjobs/scheduled-jobs/batch-job.md
        - Array jobs: runjobs/scheduled-jobs/throughput.md
        - Interactive Slurm jobs: runjobs/scheduled-jobs/interactive.md
        - Container jobs: runjobs/scheduled-jobs/container-jobs.md
        - Distribution & binding options: runjobs/scheduled-jobs/distribution-binding.md
        - Julia scheduled jobs: runjobs/scheduled-jobs/julia.md
  - Software:
    - Overview: software/index.md
    - Installing software:
      - EasyBuild: software/installing/easybuild.md
      - Spack: software/installing/spack.md
      - Container wrapper: software/installing/container-wrapper.md
    - Containers: 
      - Singularity/Apptainer containers: software/containers/singularity.md
    - Software guides:
      - VASP: software/guides/vasp.md
      - Quantum ESPRESSO: software/guides/quantumespresso.md
  - Developing:
    - Overview: development/index.md
    - Compiling:
      - Programming environment: development/compiling/prgenv.md
      - Cray compilers: development/compiling/cce.md
      - GNU compilers: development/compiling/gnu.md
    - High performance libraries: 
      - Cray libraries: development/libraries/cray-libraries.md
    - Optimizing for LUMI:
      - Using hugepages: development/optimizing/hugepages.md
    - Debugging:
      - Parallel debugging: development/debugging/gdb4hpc.md
      - Memory debugging: development/debugging/valgrind4hpc.md
      - Crash or deadlock: development/debugging/stat-atp.md
    - Performance analysis:
      - Performance analysis strategies: development/profiling/strategies.md
      - Cray Performance Analysis Tool: development/profiling/perftools.md
  - Help desk: 
    - Help desk: helpdesk/index.md
    - Training and events: helpdesk/training.md
    - Known issues: helpdesk/issues.md
    
 
theme:
  name: material
  greetings: Welcome to the LUMI Documentation
  custom_dir: mkdocs_lumi/
  language: en
  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.annotate
  
  palette:
    scheme: default
    primary: lumi
    accent: lumi

  font: false
  
  favicon: assets/favicon.png

  icon:
    logo: logo
  
  home_primary:
    title: Get Started
    page: firststeps/getstarted/
  home_secondary:
    title: To LUMI Main Page
    page: https://lumi-supercomputer.eu/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lumi-supercomputer
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LUMIhpc

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
