site_name: Documentation
repo_url: ""
edit_uri: ""
#site_url: "https://test-lumi-supercomputer-docs.rahtiapp.fi/" #hasn't been chosen yet
site_description: >-
  Instructions, user guides and tutorials for the use of the LUMI supercomputer
copyright: Copyright &copy; 2021 LUMI User Support Team
nav:
  - Intro: 
    - Welcome: index.md
  - First steps: 
    - Get Started: firststeps/getstarted-new.md
    - Access to LUMI: firststeps/accessLUMI.md
    - Setting up SSH key pair: firststeps/SSH-keys.md
    - Logging in (with SSH client): firststeps/loggingin.md
    # - LUMI web interface: firststeps/openondemand.md
    - Moving data to/from LUMI: storage/moving/scp-rsync.md
    - Next steps: firststeps/nextsteps.md
  - Hardware:
    - Hardware overview: overview/overview.md
    - Compute nodes:
      - CPU nodes - LUMI-C: computing/systems/lumic.md
      - GPU nodes - LUMI-G: computing/systems/lumig.md
      - Data analytics nodes - LUMI-D: computing/systems/lumid.md
      - Early access platform: eap/index.md
    - Storage:
      - Lustre file system: storage/parallel/lustre.md
      - Main storage - LUMI-P: storage/parallel/lumip.md
      - Flash storage - LUMI-F: storage/parallel/lumif.md
      # - Object storage - LUMI-O: storage/parallel/lumio.md
    - Interconnect: computing/interconnect.md
    # - Auxiliary platforms:
    #   - Container Orchestration Platform - LUMI-K: computing/auxiliary/lumik.md
  - Software:
    - Overview: software/index.md
    - Setup your Environment:
      - Module Environment: computing/Lmod_modules.md
      - Software stacks: computing/softwarestacks.md
    - Installing software:
      - EasyBuild: software/installing/easybuild.md
      - Python: software/installing/python.md
      - Container wrapper: software/containers/wrapper.md
    - Containers: 
      - Singularity/Apptainer containers: computing/containers.md
    # - License server: computing/license-server.md
  - Run jobs:
      - Overview: runjobs/overview.md
      - Data storage options: storage/storing-data.md
      - Billing: computing/jobs/billing.md
      - Scheduled jobs - SLURM jobs:      
        - Slurm Quickstart: computing/jobs/slurm-quickstart.md
        - Available partitions: computing/jobs/partitions.md
        - Batch jobs: computing/jobs/batch-job.md
        - Array jobs: computing/jobs/throughput.md
        - Interactive Slurm jobs: computing/jobs/interactive.md
        - Container jobs: software/containers/cray_mpich.md
        - Distribution & binding options: computing/jobs/distribution-binding.md
        - Python scheduled jobs: computing/jobs/python-jobs.md
        - Julia scheduled jobs: software/containers/julia.md
        # - Kubernetes as a scheculed job: computing/jobs/kubernetes-jobs.md
      # - Interactive jobs (via Open Ondemand):
      #   - Jupyterlab: computing/via-openondemand/jupyterlab.md
      #   - RStudio: computing/via-openondemand/rstudio.md
  #     - Serving containers: 
  #       - Something about using LUMI-K: computing/serving_containers/using-lumik.md
  - Developing:
    - Developing and Monitoring:
      - Overview: development/index.md
    - Compiling:
      - Programming environment: development/compiling/prgenv.md
      - Cray compilers: development/compiling/cce.md
      - AMD compilers: development/compiling/amd.md
      - GNU compilers: development/compiling/gnu.md
    - High performance libraries: 
      - Cray libraries: development/compiling/libraries.md
    - Optimizing for LUMI:
      - Using hugepages: development/compiling/hugepages.md
    - Debugging:
      - Parallel debugging: development/debugging/gdb4hpc.md
      - Memory debugging: development/debugging/valgrind4hpc.md
      - Crash or deadlock: development/debugging/stat-atp.md
    - Performance analysis:
      - Performance analysis strategies: development/profiling/index.md
      - CrayPat: development/profiling/perftools.md
      - Arm Forge: development/profiling/armforge.md
    - Monitoring jobs: development/monitoring/index.md
  - App guides:
    - Overview: app_guides/overview.md
    - Scientific applications:
      - VASP: software/packages/vasp.md
      - Quantum ESPRESSO: software/packages/quantumespresso.md
  - Help desk: 
    - Help desk: generic/helpdesk.md
    - About LUST (LUMI User Support Team): generic/aboutLUST.md 
    - Tech support FAQ: generic/FAQ.md
    - Known issues: issues/index.md
    - Training: generic/training.md
    - Monthly coffee breaks: generic/coffeebreaks.md
    - Service breaks: generic/service-breaks.md
    
 
theme:
  name: material
  greetings: Welcome to the LUMI Documentation
  custom_dir: mkdocs_lumi/
  language: en
  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.annotate
  
  palette:
    scheme: default
    primary: lumi
    accent: lumi

  font: false
  
  favicon: assets/favicon.png

  icon:
    logo: logo
  
  home_primary:
    title: Get Started
    page: firststeps/getstarted-new/
  home_secondary:
    title: To LUMI Main Page
    page: https://lumi-supercomputer.eu/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lumi-supercomputer
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LUMIhpc

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
