site_name: Documentation
repo_url: ""
edit_uri: ""
#site_url: "https://test-lumi-supercomputer-docs.rahtiapp.fi/" #hasn't been chosen yet
site_description: >-
  Instructions, user guides and tutorials for the use of the LUMI supercomputer
copyright: Copyright &copy; 2021 LUMI User Support Team
nav:
  - Home: index.md
  - Support:
    - Overview: support/index.md
    - Contact: support/contact.md
    - Read before you start: support/most-important.md
    - FAQ: support/faq/index.md
    - Tutorials: support/tutorials/index.md
    - Where you can get more help: support/more-support.md
    - Training material: support/training-material.md
  - Accounts:
    - Overview: accounts/index.md
    - How to create new user account: accounts/create-new-user-account.md
    - How to change password: accounts/change-password.md
    - How to manage user information: accounts/manage-user-information.md
    - How to create new project: accounts/create-new-project.md
    - How to add members to project: accounts/add-members-to-project.md
    - How to add service access for project: accounts/add-service-access-for-project.md
    - How to apply for billing units: accounts/apply-for-billing-units.md
    - How to increase disk quotas: accounts/increase-disk-quotas.md
    - How to view billing unit usage: accounts/view-billing-unit-usage.md
    - Billing: accounts/billing.md
    - How to apply for accounts in different consortia countries: accounts/account-responsible.md
  - Developing:
    - Overview: development/index.md
    - Compiling:
      - Programing environment: development/compiling/prgenv.md
      - High performance libraries: development/compiling/libraries.md
      - Compile GPU code: development/compiling/gpu.md
      - Memory optimization: development/compiling/memory.md
    - Debugging:
      - Debugging: development/debugging/gdb4hpc.md
      - Memory debugging: development/debugging/valgrind4hpc.md
      - Crash or dealock: development/debugging/stat-atp.md
    - Performance Analysis:
      - Overview: development/profiling/index.md
      - CPU: development/profiling/cpu.md
      - GPU: development/profiling/gpu.md
    - Building HPC Container: development/containers.md
  - Computing:
    - Overview: computing/index.md
    - Connecting: computing/connecting.md
    - Module environment: computing/modules.md
    - Systems:
      - CPU Partition: computing/systems/lumic.md
      - GPU Partition: computing/systems/lumig.md
    - Running jobs:
      - Overview: computing/jobs/index.md
      - Slurm Quickstart: computing/jobs/slurm-quickstart.md
      - Available partitions: computing/jobs/partitions.md
      - Batch jobs: computing/jobs/batch-job.md
      - Distribution and binding: computing/jobs/distribution-binding.md
      - High throughput: computing/jobs/throughput.md
      - Interactive usage: computing/jobs/interactive.md
      - Performance checklist: computing/jobs/performance.md
      - HPC Containers: computing/jobs/containers.md
  - Storing:
    - Overview: storage/index.md
    - HPC file systems:
      - Overview: storage/parallel/index.md
      - LUMI-P Lustre File system: storage/parallel/lumip.md
      - LUMI-F Lustre File system (Flash): storage/parallel/lumif.md
    - LUMI-O object storage:
      - Overview: storage/object/index.md
      - Introduction to LUMI-O Storage service: storage/object/intro.md
      - Accessing LUMI-O: storage/object/accessing.md
      - Common Use Cases: storage/object/use_cases.md
      - LUMI-O Clients: storage/object/clients.md
      - Common Error Messages: storage/object/error_messages.md
      - Further information: storage/object/further_info.md
      - LUMI-O object storage related terms and concepts: storage/object/terms_and_concepts.md
    - Moving data:
      - Copying files using scp: storage/moving/scp.md
      - Graphical file transfer tools: storage/moving/graphical_transfer.md
      - Using rsync for data transfer and synchronization: storage/moving/rsync.md
      - Using wget to download data from web sites to LUMI: storage/moving/wget.md
      - Remote disk mounts: storage/moving/disk_mount.md
    - Sensitive Data: storage/sensitive-data.md
  - Analyzing: 
    - Overview: data-analysis/index.md
    - Hardware: data-analysis/lumid.md
    - Remote visualization: data-analysis/remote-visualization.md
    - Python and Jupyter Notebooks: data-analysis/python-jupyter.md
    - Useful shell commands: data-analysis/commandline.md
  - Applications:
    - Overview: apps/index.md
    - In alphabetic order: apps/by_name.md
    - By discipline: apps/by_discipline.md
    - By availability: apps/by_partition.md
  - Container Services:
    - Concepts of cloud computing: container/concepts.md
    - HPC Containers: computing/jobs/containers.md
    - LUMI-K:
      - Contents: container/index.md
      - What is LUMI-K: container/lumik-what-is.md
      - Containers & their Orchestration: container/containers.md
      - Kubernetes and OpenShift concepts: container/concepts.md
      - Getting Started:
        - Getting access: container/access.md
        - Using the web interface: container/usage/getting_started.md
        - Command line tool installation and usage: container/usage/cli.md
        - Security guide: container/usage/security-guide.md
      - LUMI-K Tutorials:
        - Deploying a static web server using the web interface: container/howto/basic-console.md
        - Deploying a static web server using the command line: container/howto/elemental_tutorial.md
        - Custom domain names and secure transport: container/howto/custom-domain.md
        - Configuration, ConfigMaps and Secrets: container/howto/configuration.md
        - Webhooks: container/howto/webhooks.md
        - Reverse proxy authentication using a sidecar container: container/howto/sidecar_proxy_authentication.md
        - Short introduction to YAML: container/howto/yaml_introduction.md
        - How to transfer data to Rahti?: container/howto/transfer_data_rahti.md
        - How to add docker hub credentials to a project: container/howto/docker_hub_login.md
        - How to manually cache images in Rahti's registry: container/howto/docker_hub_manual_caching.md
      - Storage in LUMI-K:
        - Available storage options: container/storage/index.md
        - Persistent volumes: container/storage/persistent.md
        - Ephemeral storage: container/storage/ephemeral.md
        - Sending e-mail from LUMI-K: container/howto/email.md
      - Images:
        - Overview: container/images/overview.md
        - Creating an image: container/images/creating.md
      - Rahti Templates: container/template-docs.md
      - Projects and quota: container/usage/projects_and_quota.md
      - Billing: container/billing.md
      - External documentation: container/ext_docs.md
    - Docker Stack: container/docker.md

theme:
  name: material
  greetings: Welcome to the LUMI Documentation
  custom_dir: mkdocs_lumi/
  language: en

  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.instant
    - search.suggest
  
  palette:
    scheme: default
    primary: lumi
    accent: lumi

  font:
    text: canada-type-gibson
    code: Source Code Pro
  
  favicon: assets/favicon.png

  icon:
    logo: logo
  
  home_primary:
    title: Get Started
    page: support/most-important/
  home_secondary:
    title: LUMI Overview
    page: system/overview/

#extra_javascript:
#  - 'assets/javascripts/extra.js'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lumi-supercomputer
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LUMIhpc

markdown_extensions:
  - toc:
      toc_depth: 3
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

google_analytics:
  - 'UA-5406715-9'
  - 'auto'
