site_name: Pilot Documentation
repo_url: ""
edit_uri: ""
#site_url: "https://test-lumi-supercomputer-docs.rahtiapp.fi/" #hasn't been chosen yet
site_description: >-
  Instructions, user guides and tutorials for the use of the LUMI supercomputer
copyright: Copyright &copy; 2021 LUMI User Support Team
nav:
  - Home: index.md
  - Support:
    - Overview: support/index.md
    - Contact: support/contact.md
    - FAQ: support/faq/index.md
    - Tutorials: support/tutorials/index.md
    - Where you can get more help: support/more-support.md
    - Training material: support/training-material.md
  - Accounts:
    - Overview: accounts/index.md
    - How to create new user account: accounts/create-new-user-account.md
    - How to change password: accounts/change-password.md
    - How to manage user information: accounts/manage-user-information.md
    - How to create new project: accounts/create-new-project.md
    - How to add members to project: accounts/add-members-to-project.md
    - How to add service access for project: accounts/add-service-access-for-project.md
    - How to apply for billing units: accounts/apply-for-billing-units.md
    - How to increase disk quotas: accounts/increase-disk-quotas.md
    - How to view billing unit usage: accounts/view-billing-unit-usage.md
    - Billing: accounts/billing.md
    - How to apply for accounts in different consortia countries: accounts/account-responsible.md
  - Developing:
    - Overview: development/index.md
    - Compiling:
      - Programming environment: development/compiling/prgenv.md
      - Cray compilers: development/compiling/cce.md
      - GNU compilers: development/compiling/gnu.md
      - High performance libraries: development/compiling/libraries.md
      - Using hugepages: development/compiling/hugepages.md
    - Debugging:
      - Debugging: development/debugging/gdb4hpc.md
      - Memory debugging: development/debugging/valgrind4hpc.md
      - Crash or dealock: development/debugging/stat-atp.md
    - Performance Analysis:
      - Overview: development/profiling/index.md
      - CrayPat: development/profiling/perftools.md
    - Building HPC Container: development/containers.md
  - Computing:
    - Overview: computing/index.md
    - Connecting: computing/connecting.md
    - Module environment: computing/modules.md
    - Systems:
      - CPU Partition: computing/systems/lumic.md
      - GPU EAP Partition: computing/systems/kuura.md
    - Running jobs:
      - Overview: computing/jobs/index.md
      - Slurm Quickstart: computing/jobs/slurm-quickstart.md
      - Available partitions: computing/jobs/partitions.md
      - Batch jobs: computing/jobs/batch-job.md
      - Distribution and binding: computing/jobs/distribution-binding.md
      - High throughput: computing/jobs/throughput.md
      - Interactive usage: computing/jobs/interactive.md
  - Storing:
    - Overview: storage/index.md
    - Parallel file systems:
      - Overview: storage/parallel/index.md
      - Lustre: storage/parallel/lustre.md
      - LUMI-P Lustre File system: storage/parallel/lumip.md
      - LUMI-F Lustre File system (Flash): storage/parallel/lumif.md
    - Object storage:
      - Overview: storage/object/index.md
    - Moving data:
      - Copying files using scp: storage/moving/scp.md
      - Graphical file transfer tools: storage/moving/graphical_transfer.md
      - Using rsync for data transfer and synchronization: storage/moving/rsync.md
      - Using wget to download data from web sites to LUMI: storage/moving/wget.md
      - Remote disk mounts: storage/moving/disk_mount.md
 
theme:
  name: material
  greetings: Welcome to the LUMI Documentation
  custom_dir: mkdocs_lumi/
  language: en

  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.instant
    - search.suggest
  
  palette:
    scheme: default
    primary: lumi
    accent: lumi

  font:
    text: canada-type-gibson
    code: Source Code Pro
  
  favicon: assets/favicon.png

  icon:
    logo: logo
  
  home_primary:
    title: Get Started
    page: generic/getstarted/
  home_secondary:
    title: LUMI Overview
    page: generic/overview/

#extra_javascript:
#  - 'assets/javascripts/extra.js'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lumi-supercomputer
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LUMIhpc

markdown_extensions:
  - toc:
      toc_depth: 3
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

google_analytics:
  - 'UA-5406715-9'
  - 'auto'
